### ISSUE TITLE
not the best way to get you

### ISSUE THREAD

**Issue by bucky67gto** [jpf5046/betdeck#1]
I was on reddit and I see you had a go at stats/ou for baseball. Being Canadian I was looking at the same type of thing for hockey. Do you have a copy you are willing to share?

Thanks

**Comment by jpf5046** [comment]
you sent me the same message on reddit, did you not?

**Comment by bucky67gto** [comment]
I did, was trying to see if you were willing to share, but I did not know if you had been on in a while.  I am sorry to have bothered you if not.  My apologies

**Comment by jpf5046** [comment]
how much have you started on the hockey data

**Comment by bucky67gto** [comment]
Just collecting the data from sites and cleaning it up in power bi
